### ISSUE TITLE
Program crashes when driver exits race

### ISSUE THREAD

**Issue by JamesPRobertson** [JamesPRobertson/ACCRT#20]
If the user exits a race, the program encounters an exception and exits.

**Comment by JamesPRobertson** [comment]
```
Unhandled exception. System.ArgumentException: .NET number values such as positive and negative infinity cannot be written as valid JSON.
   at System.Text.Json.ThrowHelper.ThrowArgumentException_ValueNotSupported()
   at System.Text.Json.Utf8JsonWriter.WriteNumberValue(Single value)
   at System.Text.Json.Serialization.Converters.ArrayConverter`2.OnWriteResume(Utf8JsonWriter writer, TElement[] array, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at Driver.TelemetryParser.GetJSONTelemetryData() in C:\Users\james\projects\accrt\src\driver_telemetry\DriverTelemetry.cs:line 43
   at Server.TelemetryServer.ExecuteUDPServer() in C:\Users\james\projects\accrt\src\driver_telemetry\Server.cs:line 58
   at Driver.CLI.Main(String[] args) in C:\Users\james\projects\accrt\src\driver_telemetry\DriverTelemetry.cs:line 120```

**Comment by Justin-Pierre** [comment]
Potential resolution steps:

Determine how data changes on race exit
Detect this case before serialization and:
- Emulate the data output in the pre-race condition OR
- fix up the problematic fields, and inject some sort of "race end" signifier that would allow for a client to know the race has ended
